/* %Z% %W% %I% %E% %U% */
 /********************************************************************/
 /*                                                                  */
 /* Program name: AMQSVFC4                                           */
 /*                                                                  */
 /* Description: Sample C skeleton of a Data Conversion exit         */
 /*              routine                                             */
 /*                                                                  */
 /*   <copyright                                                     */
 /*   notice="lm-source-program"                                     */
 /*   pids="5724-H72,"                                               */
 /*   years="1993,2016"                                              */
 /*   crc="2864209134" >                                             */
 /*   Licensed Materials - Property of IBM                           */
 /*                                                                  */
 /*   5724-H72,                                                      */
 /*                                                                  */
 /*   (C) Copyright IBM Corp. 1993, 2016 All Rights Reserved.        */
 /*                                                                  */
 /*   US Government Users Restricted Rights - Use, duplication or    */
 /*   disclosure restricted by GSA ADP Schedule Contract with        */
 /*   IBM Corp.                                                      */
 /*   </copyright>                                                   */
 /*                                                                  */
 /*                                                                  */
 /********************************************************************/
 /*                                                                  */
 /* Function:                                                        */
 /*                                                                  */
 /*   AMQSVFC4 is a sample C skeleton of a Data Conversion exit      */
 /*   routine.                                                       */
 /*   Each Data Conversion exit routine converts a single named      */
 /*   Format.  This skeleton is intended as a wrapper for code       */
 /*   fragments generated by the Data Conversion Exit-generation     */
 /*   utility program - CVTMQMDTA.                                   */
 /*                                                                  */
 /*   The utility produces one code fragment for each data           */
 /*   structure; a format may be defined in terms of several         */
 /*   such structures so that several code fragments will need       */
 /*   to be added to this skeleton to produce a routine to do        */
 /*   data conversion of the entire Format.                          */
 /*                                                                  */
 /*   Once complete the code should be compiled into a program       */
 /*   with the name of the program being the name of the format      */
 /*   to be converted.                                               */
 /*   See the MQ documentation for further information.              */
 /*                                                                  */
 /********************************************************************/
 /*                                                                  */
 /*  AMQSVFC4 takes the parameters defined for a Data Conversion     */
 /*  exit routine in the CMQXC.H header file.                        */
 /*                                                                  */
 /********************************************************************/
 #include <cmqc.h>              /* For MQI datatypes                 */
 #include <cmqxc.h>             /* For MQI exit-related definitions  */
 #include <cmqec.h>             /* For interface function pointers   */
 #include <amqsvmha.h>          /* For sample macro definitions      */

 /********************************************************************/
 /* Insert the function prototypes for the functions produced by     */
 /* the data conversion utility program.                             */
 /********************************************************************/

 int  main  (int argc, char * argv[]);

 int  main  (int argc, char * argv[])
 {
   PMQDXP   pDataConvExitParms = (PMQDXP)   argv[1];
   PMQMD    pMsgDesc           = (PMQMD)    argv[2];
   MQLONG   InBufferLength     = *(PMQLONG) argv[3];
   PMQVOID  pInBuffer          = (PMQVOID)  argv[4];
   MQLONG   OutBufferLength    = *(PMQLONG) argv[5];
   PMQVOID  pOutBuffer         = (PMQVOID)  argv[6];

   MQLONG   ReturnCode   = MQRC_NONE;
   MQHCONN  hConn        = pDataConvExitParms->Hconn;
   MQLONG   opts         = pDataConvExitParms->AppOptions;
   PMQBYTE  in_cursor    = (PMQBYTE)pInBuffer;
   PMQBYTE  out_cursor   = (PMQBYTE)pOutBuffer;
   PMQBYTE  in_lastbyte  = (PMQBYTE)pInBuffer + InBufferLength - 1;
   PMQBYTE  out_lastbyte = (PMQBYTE)pOutBuffer + OutBufferLength - 1;
   MQLONG   MsgEncoding  = pMsgDesc->Encoding;
   MQLONG   ReqEncoding  = pDataConvExitParms->Encoding;
   MQLONG   MsgCCSID     = pMsgDesc->CodedCharSetId;
   MQLONG   ReqCCSID     = pDataConvExitParms->CodedCharSetId;
   MQLONG   CompCode     = pDataConvExitParms->CompCode;
   MQLONG   Reason       = pDataConvExitParms->Reason;

   /******************************************************************/
   /* Insert calls to the code fragments to convert the format's     */
   /* structure(s) here.                                             */
   /* ReturnCode = ConverttagSTRUCT(                                 */
   /*                         pDataConvExitParms,                    */
   /*                         &in_cursor,                            */
   /*                         &out_cursor,                           */
   /*                         in_lastbyte,                           */
   /*                         out_lastbyte,                          */
   /*                         hConn,                                 */
   /*                         opts,                                  */
   /*                         MsgEncoding,                           */
   /*                         ReqEncoding,                           */
   /*                         MsgCCSID,                              */
   /*                         ReqCCSID,                              */
   /*                         CompCode,                              */
   /*                         Reason);                               */
   /******************************************************************/


   /******************************************************************/
   /* Check whether the conversion succeeded                         */
   /******************************************************************/
   if ((ReturnCode == MQRC_NONE) ||
       (ReturnCode == MQRC_TRUNCATED_MSG_ACCEPTED))
   {
     pDataConvExitParms->ExitResponse = MQXDR_OK;
     /****************************************************************/
     /* Always return new length. Queue manager code decides         */
     /* if the new length is to be reported.                         */
     /* Warning - this assumes that out_cursor has been set up to    */
     /* point to the end of the message. Routines produced by the    */
     /* data conversion exit utility will do this BUT if you are     */
     /* writing your own routines ensure it is updated or the        */
     /* message could end up with a zero length and appear not to    */
     /* get converted!                                               */
     /****************************************************************/
     pDataConvExitParms->DataLength = (MQLONG)(out_cursor
                                         - (PMQBYTE)pOutBuffer);
   }
   /******************************************************************/
   /* Otherwise indicate that conversion of the message data failed. */
   /******************************************************************/
   else
   {
     pDataConvExitParms->ExitResponse = MQXDR_CONVERSION_FAILED;
   }
   /******************************************************************/
   /* It the message is not already truncated update comp code, and  */
   /* reason.                                                        */
   /******************************************************************/
   if (Reason != MQRC_TRUNCATED_MSG_ACCEPTED)
   {
      pDataConvExitParms->Reason = ReturnCode;

     if (ReturnCode == MQRC_NONE)
     {
       pDataConvExitParms->CompCode   = MQCC_OK;
     }
     else
     {
       pDataConvExitParms->CompCode = MQCC_WARNING;
     }
   }

   return;
 }

 /********************************************************************/
 /* Insert the functions produced by the data conversion exit        */
 /* utility program.                                                 */
 /********************************************************************/

 /********************************************************************/
 /*                                                                  */
 /* END OF AMQSVFC4                                                  */
 /*                                                                  */
 /********************************************************************/
